#!/usr/bin/env bash
# Check if there are enough arguments

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# assigning paramentals to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

#disabbling strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# checking if the transfer was successful
if [ $? -eq 0 ]
	echo "FILE WAS TRANSFERED SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILED"
fi
