#!/usr/bin/env bash
# Script that installs Nginx server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
sudo service nginx reload
