#!/usr/bin/env bash
# Script that installs Nginx server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#testing and configuration
sudo nginx -t

sudo service nginx reload
